# Generated by Django 5.0 on 2024-01-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_time_alter_appointment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.CharField(choices=[('Surgery Department', 'Surgery Department'), ('Outpatient', 'Outpatient'), ('Inpatient', 'Inpatient'), ('Intensive Care Unit', 'Intensive Care Unit'), ('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('Psychiatry', 'Psychiatry'), ('Radiology', 'Radiology'), ('Laboratory', 'Laboratory'), ('Pharmacy', 'Pharmacy'), ('Rehabilitation', 'Rehabilitation'), ('Hematology', 'Hematology'), ('Pediatrics', 'Pediatrics'), ('Oncology', 'Oncology'), ('Ophthalmology', 'Ophthalmology')], max_length=1000, null=True),
        ),
    ]
