# Generated by Django 5.0 on 2024-01-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_blog_quote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-patient']},
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('REJECT', 'Reject'), ('ACCEPT', 'Accept'), ('PENDING', 'Pending')], default='Pending', max_length=50),
        ),
    ]
