# Generated by Django 5.0 on 2024-01-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='treated',
            field=models.BooleanField(default=False),
        ),
    ]
