# Generated by Django 5.0 on 2024-06-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0022_tag_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="appointment_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
