# Generated by Django 5.0 on 2024-01-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0003_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_doctor',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Are you a Doctor?'),
        ),
    ]
